server:
  port: 8088
  servlet:
    session:
      timeout: 1200
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vote_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: 200035qwe
    #password: 204104920
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    port: 25
    protocol: smtp
    username: 1093805126@qq.com
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  type-aliases-package: com.two.vote.entity
  mapper-locations: classpath:mapper/*Mapper.xml
